import { INestApplication } from '@nestjs/common';
import { DocumentBuilder, SwaggerModule } from '@nestjs/swagger';

export function setupSwagger(app: INestApplication): void {
  const config = new DocumentBuilder()
    .setTitle('VenteApp API')
    .setDescription(
      [
        'API backend **VenteApp Bénin** — gestion commerciale offline-first.',
        '',
        '---',
        '',
        '## Authentification',
        '',
        '### Routes publiques (sans session)',
        '| Méthode | Route | Description |',
        '|---------|-------|-------------|',
        '| `GET` | `/api/auth/lock-screen/:shopId` | Données écran PIN (ECR-01) |',
        '| `POST` | `/api/auth/pin/login` | Connexion PIN (UC-01) |',
        '| `POST` | `/api/auth/setup` | Créer boutique + patron (nouvelle entreprise) |',
        '| `POST` | `/api/auth/emergency-unlock` | Déblocage d\'urgence |',
        '',
        '### Routes protégées',
        '**Obligatoire** : `Authorization: Bearer <accessToken>` (JWT)',
        '',
        '**Boutique active** : header optionnel `X-Shop-Id: <id>` (patron multi-boutiques).',
        'Sans header → boutique par défaut de la session (`user_sessions.shop_id`).',
        'Le JWT ne contient pas de `shopId`.',
        '',
        'Renouvellement : `POST /api/auth/refresh` avec `{ "refreshToken": "..." }`',
        'Déconnexion : `POST /api/auth/logout`',
        '',
        '---',
        '',
        '## Format de réponse',
        '',
        '```json',
        '{ "success": true, "data": { ... }, "timestamp": 1719225600000 }',
        '```',
        '',
        'Les erreurs métier structurées incluent un `code` (ex. `INV_NEGATIVE_STOCK`, `RBAC_INSUFFICIENT_PERMISSION`).',
        '',
        '---',
        '',
        '## Catalogue des endpoints',
        '',
        '### Module 1 — Authentification (`/api/auth`)',
        '| Route | Permission |',
        '|-------|------------|',
        '| `GET lock-screen/:shopId` | — |',
        '| `POST pin/login` | — |',
        '| `POST refresh` | — |',
        '| `POST logout` | Bearer JWT |',
        '| `POST switch-shop` | `shops:switch` (patron) |',
        '| `GET devices` | Bearer JWT (`?all=true` → `users:read`) |',
        '| `DELETE devices/:id` | Bearer JWT (propre session ou `users:read`) |',
        '| `POST setup` | — |',
        '| `POST emergency-unlock` | — |',
        '| `POST biometric/enable` | `auth:biometric:enable` |',
        '| `POST session/touch` | `auth:session:touch` |',
        '',
        '### Module Multi-boutiques (`/api/shops`)',
        '| Route | Permission |',
        '|-------|------------|',
        '| `GET /` | `shops:read` |',
        '| `GET :id` | `shops:read` |',
        '| `POST /` | `shops:create` |',
        '| `PATCH :id` | `shops:update` |',
        '| `PATCH :id/deactivate` | `shops:deactivate` |',
        '| `POST :id/set-default` | `shops:switch` |',
        '',
        '### Utilisateurs (`/api/users`)',
        '| Route | Permission |',
        '|-------|------------|',
        '| `GET /` | `users:read` |',
        '| `GET :id/assignment` | `users:read` |',
        '| `POST /` | `users:create` |',
        '| `PATCH :id/role` | `users:update_role` |',
        '| `PATCH :id/shop` | `users:assign_shop` |',
        '| `PATCH :id/deactivate` | `users:deactivate` |',
        '',
        '### RBAC (`/api/rbac`)',
        '| Route | Permission |',
        '|-------|------------|',
        '| `GET roles` | `rbac:read` |',
        '| `GET roles/:code` | `rbac:read` |',
        '| `POST roles` | `rbac:manage` |',
        '| `PATCH roles/:code` | `rbac:manage` |',
        '| `DELETE roles/:code` | `rbac:manage` |',
        '| `PUT roles/:code/permissions` | `rbac:manage` |',
        '| `GET permissions` | `rbac:read` |',
        '| `GET me` | session |',
        '| `GET check/:permission` | session |',
        '| `GET users/:userId/overrides` | `rbac:override` |',
        '| `GET users/:userId/permissions` | `rbac:read` |',
        '| `PUT users/:userId/permissions` | `rbac:override` |',
        '| `POST users/:userId/overrides` | `rbac:override` |',
        '| `DELETE users/:userId/overrides/:code` | `rbac:override` |',
        '',
        '### Module 2 — Tableau de bord (`/api/dashboard`)',
        '| Route | Permission |',
        '|-------|------------|',
        '| `GET /` | `dashboard:read` (+ `dashboard:financial` pour section financière) |',
        '',
        '### Module 3 — Inventaire',
        '**Catégories** (`/api/categories`)',
        '| Route | Permission |',
        '|-------|------------|',
        '| `GET /` | `inventory:read` |',
        '| `POST /` | `inventory:write` |',
        '| `PATCH :id` | `inventory:write` |',
        '| `DELETE :id` | `inventory:write` |',
        '',
        '**Produits** (`/api/products`)',
        '| Route | Permission |',
        '|-------|------------|',
        '| `GET /` | `inventory:read` |',
        '| `GET low-stock` | `inventory:read` |',
        '| `GET :id` | `inventory:read` |',
        '| `POST /` | `inventory:write` |',
        '| `PATCH :id` | `inventory:write` |',
        '| `PATCH :id/archive` | `inventory:archive` |',
        '| `DELETE :id` | `inventory:archive` |',
        '| `POST :id/stock-adjustments` | `inventory:adjust` |',
        '| `GET :id/stock-movements` | `inventory:read` |',
        '',
        '### Module 4 — Ventes (`/api/sales`)',
        '| Route | Permission |',
        '|-------|------------|',
        '| `GET /` | `sales:read` |',
        '| `GET :id` | `sales:read` |',
        '| `POST /` | `sales:create` (vente standard UC-05) |',
        '| `POST /quick` | `sales:create` (vente rapide RG-VTE-09) |',
        '| `PATCH :id/cancel` | `sales:cancel` (patron, UC-07) |',
        '',
        '### Module 5 — Paiements (`/api/payments`)',
        '| Route | Permission |',
        '|-------|------------|',
        '| `GET /` | `payments:read` |',
        '| `GET :id` | `payments:read` |',
        '',
        '### Module 6 — Clients (`/api/customers`)',
        '| Route | Permission |',
        '|-------|------------|',
        '| `GET /` | `customers:read` |',
        '| `GET debtors` | `customers:read` + `debts:read` (UC-11) |',
        '| `GET :id` | `customers:read` |',
        '| `GET :id/sales` | `customers:read` + `sales:read` |',
        '| `GET :id/debt-reminder` | `customers:read` (UC-10 WhatsApp) |',
        '| `POST /` | `customers:write` |',
        '| `PATCH :id` | `customers:write` |',
        '| `PATCH :id/archive` | `customers:archive` |',
        '',
        '### Module 7 — Dettes (`/api/debts`)',
        '| Route | Permission |',
        '|-------|------------|',
        '| `GET summary` | `debts:read` (UC-11) |',
        '| `GET /` | `debts:read` |',
        '| `GET :id` | `debts:read` |',
        '| `GET :id/history` | `debts:read` (UC-13) |',
        '| `POST :id/payments` | `debts:payment` + `payments:create` |',
        '| `PATCH :id/forgive` | `debts:forgive` (UC-12, patron) |',
        '',
        '### Module 8 — Statistiques & Rapports (`/api/reports`)',
        '| Route | Permission |',
        '|-------|------------|',
        '| `GET /` | `reports:read` (+ `reports:financial` pour section financière) |',
        '| Query `consolidated=true` | `shops:consolidated_read` (V3, patron) |',
        '',
        '### Module 9 — Notifications (`/api/notifications`)',
        '| Route | Permission |',
        '|-------|------------|',
        '| `GET settings` | `settings:read` |',
        '| `PATCH settings` | `settings:write` |',
        '| `GET pending` | `dashboard:read` (candidats notifications locales) |',
        '| `POST ack` | `dashboard:read` (quota rappels dette RG-NOTIF-03) |',
        '',
        '### Module 10 — Paramètres & Configuration (`/api/settings`)',
        '| Route | Permission |',
        '|-------|------------|',
        '| `GET /` | `settings:read` |',
        '| `PATCH /` | `settings:write` |',
        '| `POST backup` | `settings:write` (enregistrer sauvegarde RG-PARAM-04) |',
        '| `PATCH sync` | `settings:write` (sync cloud V2) |',
        '',
        '### Module 12 — Audit & Journal (`/api/audit`)',
        '| Route | Permission |',
        '|-------|------------|',
        '| `GET /` | `audit:read` (patron, RG-AUD-01) |',
        '| `GET filters` | `audit:read` |',
        '| `GET export` | `audit:read` (UC-22, export JSON → PDF mobile) |',
        '| `GET entities/:table/:id` | `audit:read` (RG-AUD-06) |',
        '| `GET :id` | `audit:read` |',
      ].join('\n'),
    )
    .setVersion('1.0.0')
    .setContact('VenteApp', '', 'support@venteapp.bj')
    .addBearerAuth(
      {
        type: 'http',
        scheme: 'bearer',
        bearerFormat: 'JWT',
        description: 'JWT access token obtenu via POST /api/auth/pin/login ou /api/auth/refresh. Le contexte boutique se passe via le header X-Shop-Id.',
      },
      'bearer',
    )
    .addTag('Application', 'Santé et informations générales de l\'API')
    .addTag('Authentification', 'Module 1 — PIN, biométrie, sessions et déblocage d\'urgence')
    .addTag('Rôles & Permissions', 'Catalogue RBAC, rôles boutique et overrides utilisateur')
    .addTag('Utilisateurs', 'Gestion des vendeurs et lecteurs (patron uniquement)')
    .addTag('Tableau de bord', 'Module 2 — KPIs et synthèse du jour (fuseau Bénin)')
    .addTag('Boutiques', 'Gestion multi-boutiques — création, sélection et bascule (RG-SHOP)')
    .addTag('Inventaire — Catégories', 'Module 3 — Catégories produits (ECR-02)')
    .addTag('Inventaire — Produits', 'Module 3 — Catalogue, stock, archivage et mouvements (ECR-03)')
    .addTag('Ventes', 'Module 4 — Ventes standard et rapide, reçus, annulation (ECR-04, UC-05, UC-07)')
    .addTag('Dettes', 'Module 7 — Créances, remboursements, pardon et historique audit (UC-12, UC-13)')
    .addTag('Paiements', 'Module 5 — Historique des paiements et acomptes')
    .addTag('Clients', 'Module 6 — Répertoire clients, fiches, débiteurs et rappels WhatsApp (ECR-08)')
    .addTag('Statistiques & Rapports', 'Module 8 — KPIs période, top produits, recouvrement, vue consolidée V3')
    .addTag('Notifications', 'Module 9 — Préférences et candidats pour notifications locales intelligentes')
    .addTag('Paramètres & Configuration', 'Module 10 — Boutique, sécurité, reçus, sauvegarde et sync cloud')
    .addTag('Audit & Journal', 'Module 12 — Journal des actions sensibles (patron, RG-AUD)')
    .build();

  const document = SwaggerModule.createDocument(app, config, {
    deepScanRoutes: true,
  });

  SwaggerModule.setup('api/docs', app, document, {
    customSiteTitle: 'VenteApp — Documentation API',
    swaggerOptions: {
      persistAuthorization: true,
      docExpansion: 'list',
      filter: true,
      tagsSorter: 'alpha',
      operationsSorter: 'alpha',
    },
  });
}
