export enum AuditAction {
  EMERGENCY_UNLOCK = 'emergency_unlock',
  USER_ROLE_CHANGED = 'user_role_changed',
  USER_SHOP_ASSIGNED = 'user_shop_assigned',
  RBAC_OVERRIDES_REPLACED = 'rbac_overrides_replaced',
  DEBT_CREATED = 'debt_created',
  DEBT_PAYMENT_RECORDED = 'debt_payment_recorded',
  DEBT_FORGIVEN = 'debt_forgiven',
  SALE_CREATED = 'sale_created',
  SALE_CANCELLED = 'sale_cancelled',
  STOCK_ADJUSTED = 'stock_adjusted',
  PRODUCT_PRICE_CHANGED = 'product_price_changed',
  PRODUCT_ARCHIVED = 'product_archived',
  PRODUCT_DELETED = 'product_deleted',
  CATEGORY_DELETED = 'category_deleted',
  SHOP_CREATED = 'shop_created',
  SHOP_UPDATED = 'shop_updated',
  SHOP_DEACTIVATED = 'shop_deactivated',
  SHOP_DEFAULT_SET = 'shop_default_set',
  SHOP_SWITCHED = 'shop_switched',
  CUSTOMER_ARCHIVED = 'customer_archived',
  CUSTOMER_CREATED = 'customer_created',
  CUSTOMER_UPDATED = 'customer_updated',
  SETTINGS_UPDATED = 'settings_updated',
  BACKUP_RECORDED = 'backup_recorded',
  SYNC_SETTINGS_UPDATED = 'sync_settings_updated',
}

export enum AuditModule {
  AUTH = 'auth',
  SETTINGS = 'settings',
  USERS = 'users',
  SALES = 'sales',
  DEBTS = 'debts',
  PRODUCTS = 'products',
  SHOPS = 'shops',
  CUSTOMERS = 'customers',
}
