export enum ErrorCode {
  // Auth
  AUTH_INVALID_PIN = 'AUTH_INVALID_PIN',
  AUTH_ACCOUNT_LOCKED = 'AUTH_ACCOUNT_LOCKED',
  AUTH_SESSION_REQUIRED = 'AUTH_SESSION_REQUIRED',
  AUTH_SESSION_INVALID = 'AUTH_SESSION_INVALID',
  AUTH_REFRESH_INVALID = 'AUTH_REFRESH_INVALID',
  AUTH_REFRESH_EXPIRED = 'AUTH_REFRESH_EXPIRED',
  AUTH_WHATSAPP_SEND_FAILED = 'AUTH_WHATSAPP_SEND_FAILED',

  // RBAC — autorisation
  RBAC_INSUFFICIENT_PERMISSION = 'RBAC_INSUFFICIENT_PERMISSION',
  RBAC_INSUFFICIENT_ROLE = 'RBAC_INSUFFICIENT_ROLE',
  RBAC_PERMISSION_DENIED = 'RBAC_PERMISSION_DENIED',

  // RBAC — gestion des rôles
  RBAC_ROLE_NOT_FOUND = 'RBAC_ROLE_NOT_FOUND',
  RBAC_ROLE_SYSTEM_PROTECTED = 'RBAC_ROLE_SYSTEM_PROTECTED',
  RBAC_ROLE_IN_USE = 'RBAC_ROLE_IN_USE',
  RBAC_ROLE_CODE_CONFLICT = 'RBAC_ROLE_CODE_CONFLICT',
  RBAC_INVALID_PERMISSION = 'RBAC_INVALID_PERMISSION',
  RBAC_OVERRIDE_NOT_FOUND = 'RBAC_OVERRIDE_NOT_FOUND',

  // RBAC — politique métier
  RBAC_LAST_OWNER_PROTECTED = 'RBAC_LAST_OWNER_PROTECTED',
  RBAC_SELF_ROLE_DEMOTION = 'RBAC_SELF_ROLE_DEMOTION',
  RBAC_OWNER_PROMOTION_DENIED = 'RBAC_OWNER_PROMOTION_DENIED',
  USERS_OWNER_SHOP_ASSIGN_DENIED = 'USERS_OWNER_SHOP_ASSIGN_DENIED',
  USERS_SELF_SHOP_ASSIGN_DENIED = 'USERS_SELF_SHOP_ASSIGN_DENIED',

  // Générique
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  NOT_FOUND = 'NOT_FOUND',
  CONFLICT = 'CONFLICT',
  FORBIDDEN = 'FORBIDDEN',
  INTERNAL_ERROR = 'INTERNAL_ERROR',

  // Multi-boutique
  TENANT_CONTEXT_REQUIRED = 'TENANT_CONTEXT_REQUIRED',
  TENANT_ACCESS_DENIED = 'TENANT_ACCESS_DENIED',

  // Inventaire
  INV_PRODUCT_NOT_FOUND = 'INV_PRODUCT_NOT_FOUND',
  INV_CATEGORY_NOT_FOUND = 'INV_CATEGORY_NOT_FOUND',
  INV_CATEGORY_INACTIVE = 'INV_CATEGORY_INACTIVE',
  INV_CATEGORY_NAME_CONFLICT = 'INV_CATEGORY_NAME_CONFLICT',
  INV_INVALID_PRODUCT_NAME = 'INV_INVALID_PRODUCT_NAME',
  INV_INVALID_PRICE = 'INV_INVALID_PRICE',
  INV_INVALID_STOCK = 'INV_INVALID_STOCK',
  INV_NEGATIVE_STOCK = 'INV_NEGATIVE_STOCK',
  INV_REASON_REQUIRED = 'INV_REASON_REQUIRED',
  INV_PRODUCT_ALREADY_ARCHIVED = 'INV_PRODUCT_ALREADY_ARCHIVED',
  INV_PRODUCT_DELETE_HAS_SALES = 'INV_PRODUCT_DELETE_HAS_SALES',
  INV_CATEGORY_HAS_PRODUCTS = 'INV_CATEGORY_HAS_PRODUCTS',

  // Boutiques
  SHOP_LAST_ACTIVE_PROTECTED = 'SHOP_LAST_ACTIVE_PROTECTED',
  SHOP_INACTIVE = 'SHOP_INACTIVE',
  SHOP_SWITCH_DENIED = 'SHOP_SWITCH_DENIED',

  // Ventes
  SALE_NOT_FOUND = 'SALE_NOT_FOUND',
  SALE_ALREADY_CANCELLED = 'SALE_ALREADY_CANCELLED',
  SALE_CANCEL_WINDOW_EXPIRED = 'SALE_CANCEL_WINDOW_EXPIRED',
  SALE_CANCEL_DEBT_PARTIAL = 'SALE_CANCEL_DEBT_PARTIAL',
  SALE_INSUFFICIENT_STOCK = 'SALE_INSUFFICIENT_STOCK',
  SALE_CUSTOMER_REQUIRED = 'SALE_CUSTOMER_REQUIRED',
  SALE_INVALID_PAYMENT = 'SALE_INVALID_PAYMENT',
  SALE_EMPTY_CART = 'SALE_EMPTY_CART',
  SALE_QUICK_CREDIT_DENIED = 'SALE_QUICK_CREDIT_DENIED',
  SALE_OWNER_ONLY_CANCEL = 'SALE_OWNER_ONLY_CANCEL',

  // Paiements & dettes
  PAYMENT_NOT_FOUND = 'PAYMENT_NOT_FOUND',
  PAYMENT_MOMO_REFERENCE_REQUIRED = 'PAYMENT_MOMO_REFERENCE_REQUIRED',
  DEBT_NOT_FOUND = 'DEBT_NOT_FOUND',
  DEBT_NOT_OPEN = 'DEBT_NOT_OPEN',
  DEBT_INVALID_AMOUNT = 'DEBT_INVALID_AMOUNT',
  DEBT_FORGIVE_DENIED = 'DEBT_FORGIVE_DENIED',
  DEBT_FORGIVE_REASON_TOO_SHORT = 'DEBT_FORGIVE_REASON_TOO_SHORT',
  DEBT_ALREADY_FORGIVEN = 'DEBT_ALREADY_FORGIVEN',

  // Clients
  CUSTOMER_NOT_FOUND = 'CUSTOMER_NOT_FOUND',
  CUSTOMER_INVALID_NAME = 'CUSTOMER_INVALID_NAME',
  CUSTOMER_ALREADY_ARCHIVED = 'CUSTOMER_ALREADY_ARCHIVED',
  CUSTOMER_ARCHIVE_BLOCKED = 'CUSTOMER_ARCHIVE_BLOCKED',
  CUSTOMER_DEBT_REMINDER_NO_PHONE = 'CUSTOMER_DEBT_REMINDER_NO_PHONE',
}
