export enum ErrorCode {
  // Auth
  AUTH_INVALID_PIN = 'AUTH_INVALID_PIN',
  AUTH_ACCOUNT_LOCKED = 'AUTH_ACCOUNT_LOCKED',
  AUTH_SESSION_REQUIRED = 'AUTH_SESSION_REQUIRED',
  AUTH_SESSION_INVALID = 'AUTH_SESSION_INVALID',

  // RBAC — autorisation
  RBAC_INSUFFICIENT_PERMISSION = 'RBAC_INSUFFICIENT_PERMISSION',
  RBAC_INSUFFICIENT_ROLE = 'RBAC_INSUFFICIENT_ROLE',
  RBAC_PERMISSION_DENIED = 'RBAC_PERMISSION_DENIED',

  // RBAC — gestion des rôles
  RBAC_ROLE_NOT_FOUND = 'RBAC_ROLE_NOT_FOUND',
  RBAC_ROLE_SYSTEM_PROTECTED = 'RBAC_ROLE_SYSTEM_PROTECTED',
  RBAC_ROLE_IN_USE = 'RBAC_ROLE_IN_USE',
  RBAC_ROLE_CODE_CONFLICT = 'RBAC_ROLE_CODE_CONFLICT',
  RBAC_INVALID_PERMISSION = 'RBAC_INVALID_PERMISSION',
  RBAC_OVERRIDE_NOT_FOUND = 'RBAC_OVERRIDE_NOT_FOUND',

  // RBAC — politique métier
  RBAC_LAST_OWNER_PROTECTED = 'RBAC_LAST_OWNER_PROTECTED',
  RBAC_SELF_ROLE_DEMOTION = 'RBAC_SELF_ROLE_DEMOTION',
  RBAC_OWNER_PROMOTION_DENIED = 'RBAC_OWNER_PROMOTION_DENIED',

  // Générique
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  NOT_FOUND = 'NOT_FOUND',
  CONFLICT = 'CONFLICT',
  FORBIDDEN = 'FORBIDDEN',
  INTERNAL_ERROR = 'INTERNAL_ERROR',

  // Multi-boutique
  TENANT_CONTEXT_REQUIRED = 'TENANT_CONTEXT_REQUIRED',
  TENANT_ACCESS_DENIED = 'TENANT_ACCESS_DENIED',
}
