export enum ArikeModule {
  SALES = 'SALES',
  INVENTORY = 'INVENTORY',
  EXPENSES = 'EXPENSES',
  CUSTOMERS = 'CUSTOMERS',
  DEBTS = 'DEBTS',
  CASH_SESSIONS = 'CASH_SESSIONS',
  REPORTS_BASIC = 'REPORTS_BASIC',
  REPORTS_ADVANCED = 'REPORTS_ADVANCED',
  PROCUREMENT = 'PROCUREMENT',
  SALES_ORDERS = 'SALES_ORDERS',
  STOCK_TRANSFERS = 'STOCK_TRANSFERS',
  FX_EXCHANGE = 'FX_EXCHANGE',
  AI_ASSISTANT = 'AI_ASSISTANT',
}

export enum ArikeCapability {
  CLOUD_SYNC = 'CLOUD_SYNC',
  AI_ASSISTANT = 'AI_ASSISTANT',
  MULTI_DEVICE = 'MULTI_DEVICE',
  MULTI_SHOP = 'MULTI_SHOP',
  WEB_BACKOFFICE = 'WEB_BACKOFFICE',
  API_EXPORT = 'API_EXPORT',
  CUSTOM_INTEGRATIONS = 'CUSTOM_INTEGRATIONS',
  DEDICATED_SUPPORT = 'DEDICATED_SUPPORT',
}
