-- Corrige settings.id : DEFAULT 1 bloquait toute 2e boutique (conflit settings_pkey).
-- Chaque boutique doit avoir sa propre ligne settings avec un id unique.
--
-- Les bases créées via 001_auth_schema.sql utilisent déjà
--   BIGINT GENERATED BY DEFAULT AS IDENTITY
-- → cette migration est un no-op sur un `supabase db reset` propre.
-- Elle ne s'applique qu'aux anciennes bases où id avait DEFAULT 1 (sans IDENTITY).

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'settings'
      AND column_name = 'id'
      AND is_identity = 'YES'
  ) THEN
    RETURN;
  END IF;

  ALTER TABLE settings ALTER COLUMN id DROP DEFAULT;

  CREATE SEQUENCE IF NOT EXISTS settings_id_seq;

  PERFORM setval(
    'settings_id_seq',
    COALESCE((SELECT MAX(id) FROM settings), 0) + 1,
    false
  );

  ALTER TABLE settings
    ALTER COLUMN id SET DEFAULT nextval('settings_id_seq');

  ALTER SEQUENCE settings_id_seq OWNED BY settings.id;
END $$;
